#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PYTHONPATH="$ROOT${PYTHONPATH:+:$PYTHONPATH}"
export LAM_UI_BRAND="${LAM_UI_BRAND:-Interactionface | RADRILONIUMA OS}"
export LAM_UI_THEME_WORDS="${LAM_UI_THEME_WORDS:-shadow blur light liquid glass inter front central core face}"
export LAM_UI_PROFILE="${LAM_UI_PROFILE:-touch}"
export LAM_UI_ACTIVITY_WALLPAPER="${LAM_UI_ACTIVITY_WALLPAPER:-1}"
export LAM_UI_MIRROR_FLOW_STRENGTH="${LAM_UI_MIRROR_FLOW_STRENGTH:-0.35}"
export LAM_UI_ZONE_FLOW_DECAY="${LAM_UI_ZONE_FLOW_DECAY:-1.6}"
export LAM_UI_ZONE_FLOW_INJECT="${LAM_UI_ZONE_FLOW_INJECT:-1.0}"
export LAM_UI_AUDIO_FEEDBACK="${LAM_UI_AUDIO_FEEDBACK:-1}"
export LAM_UI_HAPTIC_FEEDBACK="${LAM_UI_HAPTIC_FEEDBACK:-1}"
export LAM_UI_FEEDBACK_FLOW_THRESHOLD="${LAM_UI_FEEDBACK_FLOW_THRESHOLD:-2.6}"
export LAM_UI_FEEDBACK_MIN_INTERVAL_SEC="${LAM_UI_FEEDBACK_MIN_INTERVAL_SEC:-0.35}"
export LAM_UI_AMBIENT_LIGHT_ENABLED="${LAM_UI_AMBIENT_LIGHT_ENABLED:-1}"
export LAM_UI_AMBIENT_LIGHT_INTERVAL_SEC="${LAM_UI_AMBIENT_LIGHT_INTERVAL_SEC:-0.22}"
export LAM_UI_AMBIENT_LIGHT_MAX_BRIGHTNESS="${LAM_UI_AMBIENT_LIGHT_MAX_BRIGHTNESS:-100}"

# Keep UI responsive but calm on WSL/portable hardware.
if grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null; then
  export LAM_CONSOLE_FRAME_INTERVAL_SEC="${LAM_CONSOLE_FRAME_INTERVAL_SEC:-0.10}"
  export LAM_CONSOLE_IDLE_FRAME_INTERVAL_SEC="${LAM_CONSOLE_IDLE_FRAME_INTERVAL_SEC:-0.45}"
  export LAM_CONSOLE_INPUT_TIMEOUT_MS="${LAM_CONSOLE_INPUT_TIMEOUT_MS:-90}"
  export LAM_CONSOLE_HEALTH_POLL_SEC="${LAM_CONSOLE_HEALTH_POLL_SEC:-16}"
fi
export LAM_UI_HOVER_EXPAND_DELAY_SEC="${LAM_UI_HOVER_EXPAND_DELAY_SEC:-0.30}"
export LAM_UI_ZOOM_STEP1_DELAY_SEC="${LAM_UI_ZOOM_STEP1_DELAY_SEC:-0.70}"
export LAM_UI_ZOOM_STEP2_DELAY_SEC="${LAM_UI_ZOOM_STEP2_DELAY_SEC:-1.40}"
export LAM_UI_MAX_TAB_EXPAND="${LAM_UI_MAX_TAB_EXPAND:-3}"

exec python3 "$ROOT/apps/lam_console/app.py" "$@"
